services:
  postgres:
    image: postgres:17-alpine
    container_name: ordero-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ordero
      POSTGRES_USER: ordero
      POSTGRES_PASSWORD: ordero

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
